# -*- coding: utf-8 -*-
from selenium import webdriver
from selenium.webdriver.common.by import By
from selenium.webdriver.common.keys import Keys
from selenium.webdriver.support.ui import Select
from selenium.common.exceptions import NoSuchElementException
from selenium.common.exceptions import NoAlertPresentException
import unittest, time, re
import logging, os

class CreatePassanger(unittest.TestCase):
    def setUp(self):
        options = webdriver.ChromeOptions()
        options.add_argument("--start-maximized")
        self.driver = webdriver.Chrome("C:/Users/user/Downloads/chromedriver.exe")
        self.driver.set_window_size(1024, 600)
        self.driver.maximize_window()
        self.driver.implicitly_wait(60)
        self.verificationErrors = []
        self.accept_next_alert = True

    def test_create_passanger(self):
        driver = self.driver
        #driver.get("http://195.19.96.255:8981/documents/")
        driver.get("http://test.rpn19.ru/business/dashboard/dashboard.xhtml")
        #driver.get("http://127.0.0.1:48080/business/dashboard/dashboard.xhtml")
        #driver.get("https://rpn19.ru/documents/")
        driver.find_element(By.ID,"form:usernameInput").click()
        driver.find_element(By.ID,"form:usernameInput").clear()
        driver.find_element(By.ID,"form:usernameInput").send_keys("borisova")
        driver.find_element(By.ID,"form:passwordInput").click()
        driver.find_element(By.ID,"form:passwordInput").clear()
        driver.find_element(By.ID,"form:passwordInput").send_keys("Gi8BbtDN")
        driver.find_element(By.CSS_SELECTOR,"span.ui-button-text.ui-c").click()
        driver.find_element(By.CSS_SELECTOR,"#j_idt70 > div.nano.layout-tabmenu-nav > ul > li:nth-child(4) > a > div").click()
        driver.find_element(By.ID,"tableForm:j_idt79").click()
        driver.find_element(By.ID,"itemForm:tabView:lastName").click()
        driver.find_element(By.ID,"itemForm:tabView:lastName").clear()
        driver.find_element(By.ID,"itemForm:tabView:lastName").send_keys(u"СаблинПасс89")
        driver.find_element(By.ID,"itemForm:tabView:firstName").click()
        driver.find_element(By.ID,"itemForm:tabView:firstName").clear()
        driver.find_element(By.ID,"itemForm:tabView:firstName").send_keys(u"Роман")
        driver.find_element(By.ID,"itemForm:tabView:patronymicName").click()
        driver.find_element(By.ID,"itemForm:tabView:patronymicName").clear()
        driver.find_element(By.ID,"itemForm:tabView:patronymicName").send_keys(u"Евгеньевич")
        driver.find_element(By.ID,"itemForm:tabView:birthDate_input").click()
        driver.find_element(By.ID,"itemForm:tabView:birthDate_input").clear()
        for date in "08911111":
          driver.find_element(By.ID,"itemForm:tabView:birthDate_input").send_keys(Keys.HOME, date)
        driver.find_element(By.CSS_SELECTOR,"body").click()
        driver.find_element(By.XPATH,'//label[@for="itemForm:tabView:sex:0"]').click()
        #time.sleep(3)
        #driver.find_element(By.CSS_SELECTOR,"label.itemForm:tabView:sex:0").click()
        driver.find_element(By.ID,"itemForm:tabView:flightNumber").click()
        driver.find_element(By.ID,"itemForm:tabView:flightNumber").clear()
        driver.find_element(By.ID,"itemForm:tabView:flightNumber").send_keys(u"7845ап")
        driver.find_element(By.ID,"itemForm:tabView:seat").click()
        driver.find_element(By.ID,"itemForm:tabView:seat").clear()
        driver.find_element(By.ID,"itemForm:tabView:seat").send_keys(u"74п")
        driver.find_element(By.ID,"itemForm:tabView:departureCountry_label").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:departureCountry_items").click()
        driver.find_element(By.ID,"itemForm:tabView:departureCountry_1").click()
        driver.find_element(By.ID,"itemForm:tabView:arrivalCity_label").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:arrivalCity_items").click()
        driver.find_element(By.ID,"itemForm:tabView:arrivalCity_1").click()
        driver.find_element(By.ID,"itemForm:tabView:borderCrossingDate_input").click()
        driver.find_element(By.ID,"itemForm:tabView:borderCrossingDate_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:borderCrossingDate_input").send_keys("11.11.2020")
        driver.find_element(By.ID,"itemForm:tabView:passportSerialNumber").clear()
        driver.find_element(By.ID,"itemForm:tabView:passportSerialNumber").send_keys("1458")
        driver.find_element(By.ID,"itemForm:tabView:passportNumber").click()
        driver.find_element(By.ID,"itemForm:tabView:passportNumber").clear()
        driver.find_element(By.ID,"itemForm:tabView:passportNumber").send_keys("478965")
        driver.find_element(By.ID,"itemForm:tabView:passportDateOfIssue_input").click()
        driver.find_element(By.ID,"itemForm:tabView:passportDateOfIssue_input").clear()
        for date in "51021111":
          driver.find_element(By.ID,"itemForm:tabView:passportDateOfIssue_input").send_keys(Keys.HOME, date)
        driver.find_element(By.CSS_SELECTOR,"body").click()
        driver.find_element(By.ID,"itemForm:tabView:phoneNumber").clear()
        driver.find_element(By.ID,"itemForm:tabView:phoneNumber").send_keys("89654123654")
        driver.find_element(By.ID,"itemForm:tabView:registerSubjectRf_link").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:registerSubjectRf_label").click()
        driver.find_element(By.ID,"itemForm:tabView:registerSubjectRf_1").click()
        driver.find_element(By.ID,"itemForm:tabView:registerLocality_input").click()
        driver.find_element(By.ID,"itemForm:tabView:registerLocality_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:registerLocality_input").send_keys(u"Ярославль"+Keys.TAB)
        #driver.find_element(By.CSS_SELECTOR,"li.ui-autocomplete-item.ui-autocomplete-list-item.ui-corner-all.ui-state-highlight").click()
        driver.find_element(By.ID,"itemForm:tabView:registerCityArea_label").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:registerCityArea_items").click()
        driver.find_element(By.ID,"itemForm:tabView:registerCityArea_1").click()
        driver.find_element(By.ID,"itemForm:tabView:registerStreet_input").click()
        driver.find_element(By.ID,"itemForm:tabView:registerStreet_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:registerStreet_input").send_keys(u"Мира")
        driver.find_element(By.ID,"itemForm:tabView:registerBuilding_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:registerBuilding_input").send_keys("12")
        driver.find_element(By.ID,"itemForm:tabView:registerApartment").click()
        driver.find_element(By.ID,"itemForm:tabView:registerApartment").clear()
        driver.find_element(By.ID,"itemForm:tabView:registerApartment").send_keys("Barcode_Verification")
        driver.find_element(By.ID,"itemForm:tabView:factSubjectRf_label").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:factSubjectRf_label").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:factSubjectRf_items").click()
        #time.sleep(2)
        #driver.find_element(By.ID,"itemForm:tabView:factSubjectRf_1").click()
        driver.find_element(By.ID,"itemForm:tabView:factLocality_input").click()
        driver.find_element(By.ID,"itemForm:tabView:factLocality_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:factLocality_input").send_keys(u"Ярославль"+Keys.TAB)
        #driver.find_element(By.XPATH,"//span[@id='itemForm:tabView:factLocality_panel']/ul/li").click()
        driver.find_element(By.ID,"itemForm:tabView:factCityArea_label").click()
        driver.find_element(By.CSS_SELECTOR,"#itemForm\:tabView\:factCityArea_items").click()
        driver.find_element(By.ID,"itemForm:tabView:factCityArea_1").click()
        driver.find_element(By.ID,"itemForm:tabView:factStreet_input").click()
        driver.find_element(By.ID,"itemForm:tabView:factStreet_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:factStreet_input").send_keys(u"Мира")
        driver.find_element(By.ID,"itemForm:tabView:factBuilding_input").clear()
        driver.find_element(By.ID,"itemForm:tabView:factBuilding_input").send_keys("2"+Keys.TAB)
        driver.find_element(By.CSS_SELECTOR,"body.main-body").click()
        driver.find_element(By.ID,"itemForm:tabView:factApartment").clear()
        driver.find_element(By.ID,"itemForm:tabView:factApartment").send_keys("Barcode_Verification")
        #driver.find_element(By.XPATH,"//button[@id='itemForm:tabView:j_id110']/span[2]").click()
        driver.find_element(By.CSS_SELECTOR,"body.main-body").send_keys(Keys.CONTROL + Keys.HOME)
        time.sleep(2)
        driver.find_element(By.ID,"itemForm:j_id4").click()
        driver.find_element(By.ID,"tableForm:j_idt79")
    


if __name__ == "__main__":
    unittest.main()
